# Generated by Django 4.2.4 on 2023-08-12 18:21

from django.db import migrations

def migrer_artiste(apps, schema):
    # On récupère les modèles
    Morceau = apps.get_model('musiques', 'Morceau')
    Artiste = apps.get_model('musiques', 'Artiste')

    # On récupère les artistes déjà enregsitrés dans la table Morceau
    # Voir la documentation :
    # - https://docs.djangoproject.com/fr/3.1/ref/models/querysets/#all
    # - https://docs.djangoproject.com/fr/3.1/ref/models/querysets/#values
    # - https://docs.djangoproject.com/fr/3.1/ref/models/querysets/#distinct
    artistes_connus = [fields['artiste'] for fields in Morceau.objects.all().values('artiste').distinct()]
    
    # On peuple la table Artiste
    for artiste in artistes_connus:
        Artiste.objects.create(nom=artiste)

def annuler_migrer_artiste(apps, schema):
    Artiste = apps.get_model('musiques', 'Artiste')
    Artiste.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0002_artiste_morceau_date_sortie'),
    ]

    operations = [
        migrations.RunPython(migrer_artiste,reverse_code=annuler_migrer_artiste)
    ]
