# Generated by Django 4.2.4 on 2023-08-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0003_auto_20230812_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='fk_artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musiques.artiste'),
        ),
    ]
