# Generated by Django 4.2.4 on 2023-08-12 18:49

from django.db import migrations

def maj_fk_artiste(apps, schema):
    # On récupère les modèles
    Morceau = apps.get_model('musiques', 'Morceau')
    Artiste = apps.get_model('musiques', 'Artiste')

    # On récupère les morceaux (le champ artiste) déjà enregsitrés dans la table Morceau
    morceaux_connus = [fields['artiste'] for fields in Morceau.objects.all().values('artiste').distinct()]

    # On met à jour la table Morceau en positionnant la Fk=artiste
    for nom_artiste in morceaux_connus:
        obj = Morceau.objects.get(artiste=nom_artiste)
        artiste=Artiste.objects.get(nom=nom_artiste)
        obj.fk_artiste=artiste
        obj.save()
        


def annuler_maj_fk_artiste(apps, schema):
    Morceau = apps.get_model('musiques', 'Morceau')
    morceaux_connus = [fields['artiste'] for fields in Morceau.objects.all()]
  # On met à jour la table Morceau en positionnant la Fk à vide
    for nom_artiste in morceaux_connus:
        obj = Morceau.objects.get(artiste=nom_artiste)
        obj.fk_artiste = None
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0004_morceau_fk_artiste'),
    ]

    operations = [
        migrations.RunPython(maj_fk_artiste,reverse_code=annuler_maj_fk_artiste)
    ]
