# Generated by Django 4.2.4 on 2023-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0005_auto_20230812_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='artiste',
        ),
        migrations.AlterField(
            model_name='morceau',
            name='fk_artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiques.artiste'),
        ),
    ]
